import image1 from "../../assets/avatarimage.png";

const data = [
  {
    image: image1,
    title: "Armando",
    experience: "3 Years Experience",
    detail: "Real estate agent",
    number: "+1 234 567 890",
  },
  {
    image: image1,
    title: "Armando",
    experience: "3 Years Experience",
    detail: "Real estate agent",
    number: "+1 234 567 890",
  },
  {
    image: image1,
    title: "Armando",
    experience: "3 Years Experience",
    detail: "Real estate agent",
    number: "+1 234 567 890",
  },
  {
    image: image1,
    title: "Armando",
    experience: "3 Years Experience",
    detail: "Real estate agent",
    number: "+1 234 567 890",
  },
  {
    image: image1,
    title: "Armando",
    experience: "3 Years Experience",
    detail: "Real estate agent",
    number: "+1 234 567 890",
  },
  {
    image: image1,
    title: "Armando",
    experience: "3 Years Experience",
    detail: "Real estate agent",
    number: "+1 234 567 890",
  },
  {
    image: image1,
    title: "Armando",
    experience: "3 Years Experience",
    detail: "Real estate agent",
    number: "+1 234 567 890",
  },
  {
    image: image1,
    title: "Armando",
    experience: "3 Years Experience",
    detail: "Real estate agent",
    number: "+1 234 567 890",
  },
  {
    image: image1,
    title: "Armando",
    experience: "3 Years Experience",
    detail: "Real estate agent",
    number: "+1 234 567 890",
  },
  {
    image: image1,
    title: "Armando",
    experience: "3 Years Experience",
    detail: "Real estate agent",
    number: "+1 234 567 890",
  },
  {
    image: image1,
    title: "Armando",
    experience: "3 Years Experience",
    detail: "Real estate agent",
    number: "+1 234 567 890",
  },
  {
    image: image1,
    title: "Armando",
    experience: "3 Years Experience",
    detail: "Real estate agent",
    number: "+1 234 567 890",
  },
  {
    image: image1,
    title: "Armando",
    experience: "3 Years Experience",
    detail: "Real estate agent",
    number: "+1 234 567 890",
  },
  {
    image: image1,
    title: "Armando",
    experience: "3 Years Experience",
    detail: "Real estate agent",
    number: "+1 234 567 890",
  },
  {
    image: image1,
    title: "Armando",
    experience: "3 Years Experience",
    detail: "Real estate agent",
    number: "+1 234 567 890",
  },
];
export default data;
